### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by aphedges**
As a follow-up to #28, I have fixed some more typos in the codebase.

I also updated the JAR version in `package.sh` so it would build properly.

### CODE REVIEW

**Review by MarcCote — APPROVED** [review]
Thanks a lot. LGTM. @PeterAJansen I'll let check it out before merging.

**Comment by PeterAJansen** [comment]
Looks good, most of these typos are in the code comments. 

There is also a change to the JAR file version.  Can you verify this is accurate @MarcCote ?

**Comment by aphedges** [comment]
@PeterAJansen, the JAR file version was changed in ce05307115a099d1cf9d905a4f9d1da47cdf9ddc. That commit missed changing the build script, so I fixed it here.

**Comment by MarcCote** [comment]
Yes, I have the same change in my local version. We can merge.

-Marc-

**Pull request merged**
